services:
  postgres:
    image: postgres:16
    container_name: pg_snowflake
    restart: unless-stopped

    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: bigdata

    ports:
      - "55432:5432"

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/data
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labuser -d bigdata"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
